//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public int TypeAccount { get; set; }
        public string DisplayName { get; set; }
        public string ID_Staff { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
